---
- name: 部署blog
  hosts: web
  vars:
    databse_name: "ssadmin"
    proj_name: ssadmin
    proj_path: "/data/prd/{{proj_name}}"
    venv_path: "{{proj_path}}/venv"
    reqs_path: "{{proj_path}}/requirements.txt"
    repo_url: "git://github.com/daimon99/{{proj_name}}"
    gunicorn_port: 9028
    domains:
      - www.daimon.cc
  vars_files:
    - secrets.yml
  roles:
    - role: sysbase
  tasks:
    - file: path={{ item }} state=directory
      with_items:
        - "{{ proj_path }}"
        - "{{ proj_path }}/logs"
    - git: repo={{ repo_url }}
           dest={{ proj_path }}
           force=Yes
      tags:
        - quick
        - sync
    - pip: name={{ item }}
      with_items:
        - virtualenv
    - pip: "requirements={{ reqs_path }} virtualenv={{ venv_path }}"
    - django_manage:
        command: "{{ item }}"
        app_path: "{{ proj_path }}/src"
        virtualenv: "{{ venv_path }}"
      with_items:
        - makemigrations
        - migrate
        - collectstatic
      tags:
        - quick
    - name: 创建admin用户
      script: scripts/setadmin.py
      environment:
        PATH: "{{ venv_path }}/bin"
        PROJECT_DIR: "{{ proj_path }}/src"
        ADMIN_PASSWORD: "{{ admin_pass }}"
    - name: 检查ssadmin服务状态
      command: lsof -i:{{ gunicorn_port }}
      register: server_started
      ignore_errors: True
      tags:
        - quick
    - debug: var="server_started.stdout_lines"
    - name: 启动ssadmin服务
      shell: "{{ proj_path }}/bin/start.sh"
      args:
        chdir="{{proj_path}}/bin/"
      when: not server_started.stdout
      tags:
        - quick
    - name: 更新nginx配置文件
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/conf.d/{{ proj_name }}_prd.conf
      become: true
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted


