---
- name: 部署blog
  hosts: web
  vars:
    databse_name: "ssadmin"
    proj_name: ssadmin
    proj_path: "/data/prd/{{proj_name}}"
    venv_path: "{{proj_path}}/venv"
    reqs_path: "{{proj_path}}/requirements.txt"
    repo_url: "git://github.com/daimon99/{{proj_name}}"
    gunicorn_port: 9028
    domains:
      - sg.daimon.cc
  vars_files:
    - secrets.yml
  roles:
    - role: daimon99.sysbase
  tasks:
    - file: path={{proj_path}} state=directory
    - git: repo={{repo_url}}
           dest={{proj_path}}
    - pip: name={{ item }}
      with_items:
        - virtualenv
      tags:
        - quick
    - pip: "requirements={{ reqs_path }} virtualenv={{ venv_path }}"
      tags:
        - quick
    - django_manage:
        command: "{{item}}"
        app_path: "{{proj_path}}/src"
        virtualenv: "{{venv_path}}"
      with_items:
        - makemigrations
        - migrate
        - collectstatic

    - name: 更新nginx配置文件
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/conf.d/{{proj_name}}_prd.conf
      become: true
      notify: restart nginx



