# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(choices=[('\u5fae\u4fe1', '\u5fae\u4fe1')], default='\u5fae\u4fe1', max_length=20)),
                ('pay_id', models.CharField(help_text='\u652f\u4ed8\u6d41\u6c34', max_length=200)),
                ('pay_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('\u652f\u4ed8\u4e2d', '\u652f\u4ed8\u4e2d'), ('\u652f\u4ed8\u6210\u529f', '\u652f\u4ed8\u6210\u529f'), ('\u652f\u4ed8\u5931\u8d25', '\u652f\u4ed8\u5931\u8d25')], default='\u652f\u4ed8\u4e2d', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pay_for', models.CharField(blank=True, help_text='\u652f\u4ed8\u5bf9\u8c61\u7684id', max_length=100, null=True)),
                ('pay_memo', models.CharField(blank=True, choices=[('\u8ba2\u5355', '\u8ba2\u5355'), ('\u5145\u503c', '\u5145\u503c')], help_text='\u652f\u4ed8\u8bf4\u660e', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('\u5f85\u652f\u4ed8', '\u5f85\u652f\u4ed8'), ('\u652f\u4ed8\u6210\u529f', '\u652f\u4ed8\u6210\u529f'), ('\u652f\u4ed8\u5931\u8d25', '\u652f\u4ed8\u5931\u8d25'), ('\u5df2\u7528\u5b8c', '\u5df2\u7528\u5b8c')], default='\u5f85\u652f\u4ed8', max_length=20)),
                ('buy_on', models.DateTimeField(blank=True, null=True)),
                ('pay_on', models.DateTimeField(blank=True, null=True)),
                ('qty', models.IntegerField(default=1, help_text='\u8d2d\u4e70\u6d41\u91cf\u5927\u5c0f\u3002\u4ee5G\u4e3a\u5355\u4f4d')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('remaining', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('flow_limit', models.IntegerField(default=0)),
                ('flow_used', models.IntegerField(default=0)),
                ('flow_remaining', models.IntegerField(default=0)),
                ('flow_last_update_time', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('up_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='down_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ss_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
