# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flow_add_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='flow_update_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FlowUseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('port', models.IntegerField()),
                ('limit', models.BigIntegerField()),
                ('remaining', models.BigIntegerField()),
                ('used', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='password_change_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ssuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='ssuser',
            name='up_user',
        ),
        migrations.AddField(
            model_name='flow_add_history',
            name='ssuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssadmin.SSUser'),
        ),
    ]
